import 'package:get/get.dart';

class LocaleString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          "language_description": "English",
          "english": "English",
          "arabic":"عربي",
          "app_name": "Taajeer Finance",
          "select_language": "Select Language",
          "intro_title": "Easy Procedures",
          "intro_description":
              "We provide easy financing \n for your ambitions and needs",
          "intro_title_two": "With Taajeer Finance Services",
          "intro_description_two":
              "We can finance you to buy goods and rent cars",
          "register_now": "Register now",
          "register_des": "So you can easily get the financing you need",
          "login": "Login",
          "sign_up": "Sign Up",
          "id_or_residence": "ID or residence card number",
          "continue": "Continue",
          "mobile_check": "Mobile Check",
          "absher_check": "Absher Check",
          "login_code": "Login Code",
          "enter_code": "Please enter The code sent \n to your mobile phone",
          "sec": "sec",
          "phone_no": "Phone No",
          "date_of_birth": "Date of Birth",
          "hijri_calendar": "Hijri calendar",
          "email": "Email",
          "email_hit": "Example@Example.com",
          "i_agree_policy": "I agree to the privacy policy",
          "reset_code": "Reset Login Code",
          "send": "Send",
          "cancel": "Cancel",
          "welcome": "Welcome",
          "welcome_title": "A Client of Taajeer Finance",
          "welcome_des": "You can now log in and benefit from our services",
          "save_id_no": "Save the ID number",
          "dont_have_account": "Don't have an account?",
          "sign_up_now": "Sign Up Now",
          "access_code": "Please enter your 6-digit access code",
          "forgot_code": "Forgot your Login code?",
          "express_login": "Express Login Options",
          "face_print": "Face Print",
          "finger_print": "Finger Print",
          "temporary_access": "Temporary Access Code \n SMS",
        },

        'ar_DZ': {
          "language_description": "عربي",
          "english": "English",
          "arabic":"عربي",
          "app_name": "تاجير للتمويل",
          "select_language": "Select Language",
          "intro_title": "إجراءات سهلة",
          "intro_description":
              "نحن نقدم تمويلاً سهلاً \ n لطموحاتك واحتياجاتك",
          "intro_title_two": "With Taajeer Finance Services",
          "intro_description_two":
              "We can finance you to buy goods and rent cars",
          "register_now": "Register now",
          "register_des": "So you can easily get the financing you need",
          "login": "Login",
          "sign_up": "Sign Up",
          "id_or_residence": "ID or residence card number",
          "continue": "Continue",
          "mobile_check": "Mobile Check",
          "absher_check": "Absher Check",
          "login_code": "Login Code",
          "enter_code": "Please enter The code sent \n to your mobile phone",
          "sec": "sec",
          "phone_no": "Phone No",
          "date_of_birth": "Date of Birth",
          "hijri_calendar": "Hijri calendar",
          "email": "Email",
          "email_hit": "Example@Example.com",
          "i_agree_policy": "I agree to the privacy policy",
          "reset_code": "Reset Login Code",
          "send": "Send",
          "cancel": "Cancel",
          "welcome": "Welcome",
          "welcome_title": "A Client of Taajeer Finance",
          "welcome_des": "You can now log in and benefit from our services",
          "save_id_no": "Save the ID number",
          "dont_have_account": "Don't have an account?",
          "sign_up_now": "Sign Up Now",
          "access_code": "Please enter your 6-digit access code",
          "forgot_code": "Forgot your Login code?",
          "express_login": "Express Login Options",
          "face_print": "Face Print",
          "finger_print": "Finger Print",
          "temporary_access": "Temporary Access Code \n SMS",
        },
      };
}
